---
- name: Run apt update
  apt: update_cache=yes

- name: Install base packages
  apt: pkg={{ item }} state=installed
  with_items:
    - vim
    - git
    - screen
    - htop
    - iftop
    - python-dev
    - python-pip
    - python-virtualenv
    - ntp
  tags:
    - packages
