---
- name: Copy app nginx config
  template: src=ponger.nginx.cfg.j2
            dest=/etc/nginx/sites-available/ponger
            mode=0644 owner=root group=root
  notify: reload nginx

- name: Activate app
  file: src=/etc/nginx/sites-available/ponger
        dest=/etc/nginx/sites-enabled/ponger
        state=link
  notify: reload nginx
